#!/usr/bin/env bash
set -euo pipefail
: "${GH_TOKEN:?GH_TOKEN is required}";: "${GITHUB_REPOSITORY:?GITHUB_REPOSITORY is required}"
MAX_AGE_HOURS="${BRANCH_MAX_AGE_HOURS:-2}";CURRENT_BRANCH="${GITHUB_REF_NAME:-}";NOW_EPOCH="$(date -u +%s)";DELETED=0;KEPT=0
is_protected_branch(){ case "$1" in main|ota|codex/release-current|anderson-android-icon-release|anderson-play-icon-v1.0.1|build/silverado-aaos|codex/silverado-*|codex/anderson-android-v1) return 0;;*) return 1;;esac; }
is_anderson_work_branch(){ case "$1" in automation/*|cleanup/*|cleanup-staging*|staging/*|publish/*|work/*|diag/*|codex/v*|codex/anderson-*|codex/release-*|codex/full-code-audit-*|codex/daily-*|codex/lighting-test-*|codex/remove-*|codex/release-cleanup-*|codex/system-monitor-*|codex/white-calibration-*) return 0;;*) return 1;;esac; }
# Fail closed: inability to inspect PRs or workflow activity must never cause deletion.
OPEN_PR_JSON="$(gh api --paginate "/repos/$GITHUB_REPOSITORY/pulls?state=open&per_page=100")" || { echo 'PR inspection failed; deleting nothing';exit 1; }
has_open_pr(){ jq -e --arg b "$1" '.[]|select(.head.repo.full_name==env.GITHUB_REPOSITORY and .head.ref==$b)' <<<"$OPEN_PR_JSON" >/dev/null; }
has_active_run(){ local b="$1";local json;json="$(gh api "/repos/$GITHUB_REPOSITORY/actions/runs?branch=$(printf %s "$b"|jq -sRr @uri)&per_page=20")" || return 0;jq -e '.workflow_runs[]|select(.status=="queued" or .status=="in_progress" or .status=="waiting" or .status=="requested" or .status=="pending")' <<<"$json" >/dev/null; }
in_main(){ local sha="$1";git fetch origin main --quiet;git merge-base --is-ancestor "$sha" origin/main; }
delete_if_safe(){ local branch="$1";is_protected_branch "$branch"&&return 1;has_open_pr "$branch"&&return 1;has_active_run "$branch"&&return 1;local sha;sha="$(gh api "/repos/$GITHUB_REPOSITORY/branches/$branch" --jq '.commit.sha')"||return 1;in_main "$sha"||return 1;echo "Deleting integrated inactive Anderson branch: $branch";gh api --method DELETE "/repos/$GITHUB_REPOSITORY/git/refs/heads/$branch";DELETED=$((DELETED+1));return 0; }
mapfile -t BRANCHES < <(gh api --paginate "/repos/$GITHUB_REPOSITORY/branches?per_page=100" --jq '.[].name') || { echo 'Branch inspection failed; deleting nothing';exit 1; }
for branch in "${BRANCHES[@]:-}";do [[ -n "$branch" ]]||continue;is_protected_branch "$branch"&&continue;is_anderson_work_branch "$branch"||continue;[[ "$branch" == "$CURRENT_BRANCH" ]]&&continue;sha="$(gh api "/repos/$GITHUB_REPOSITORY/branches/$branch" --jq '.commit.sha' 2>/dev/null)"||continue;committed="$(gh api "/repos/$GITHUB_REPOSITORY/commits/$sha" --jq '.commit.committer.date' 2>/dev/null)"||continue;age_hours=$(( (NOW_EPOCH-$(date -u -d "$committed" +%s))/3600 ));if [[ "$branch" == "${DELETE_BRANCH:-}" ]]||((age_hours>=MAX_AGE_HOURS));then delete_if_safe "$branch"||{ echo "Keeping unsafe/unintegrated/active branch: $branch";KEPT=$((KEPT+1));};else KEPT=$((KEPT+1));fi;done
echo "Anderson branch cleanup complete: deleted=$DELETED kept=$KEPT"
