#include "RemoteUpdate.h"
#include <ArduinoJson.h>
#include <HTTPClient.h>
#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <mbedtls/base64.h>
#include <mbedtls/pk.h>
#include <mbedtls/sha256.h>

static constexpr const char* OTA_MANIFEST_URL="https://raw.githubusercontent.com/jlc3718-source/CETELUMA_NanoC6_WiFi_BLE_Bridge2/ota/latest.json";
static constexpr const char* OTA_RELEASE_PREFIX="https://github.com/jlc3718-source/CETELUMA_NanoC6_WiFi_BLE_Bridge2/releases/download/anderson-v";
static constexpr size_t OTA_SLOT_BYTES=0x1E0000;
static constexpr const char OTA_PUBLIC_KEY[]=R"KEY(-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE3Dw/xqxEPbvkJQAcMeZxBAxwujxN
kuGHPepzClPYMrJ4h5r8iNlyUFpJZcPI/FXe8+atedYKpIZZB5XlOj964Q==
-----END PUBLIC KEY-----
)KEY";
struct RemoteStatus{bool checked=false,ok=false,signatureValid=false,updateAvailable=false;int httpStatus=0;size_t bytes=0;String availableVersion,sha256,commit,url,message="Not checked yet";};
static RemoteStatus last;
static bool allHex(const String&s,size_t n){if(s.length()!=n)return false;for(size_t i=0;i<s.length();i++){char c=s[i];if(!((c>='0'&&c<='9')||(c>='a'&&c<='f')||(c>='A'&&c<='F')))return false;}return true;}
struct VersionParts{int major=0,minor=0,patch=0;char suffix=0;bool valid=false;};
static VersionParts parseVersion(const String&input){VersionParts v;String s=input;s.trim();int p1=s.indexOf('.'),p2=p1<0?-1:s.indexOf('.',p1+1);if(p1<=0||p2<=p1+1)return v;String a=s.substring(0,p1),b=s.substring(p1+1,p2),c=s.substring(p2+1);if(c.length()&&c[c.length()-1]>='a'&&c[c.length()-1]<='z'){v.suffix=c[c.length()-1];c.remove(c.length()-1);}auto digits=[](const String&x){if(!x.length())return false;for(size_t i=0;i<x.length();i++)if(x[i]<'0'||x[i]>'9')return false;return true;};if(!digits(a)||!digits(b)||!digits(c))return v;v.major=a.toInt();v.minor=b.toInt();v.patch=c.toInt();v.valid=true;return v;}
static int compareVersion(const String&a,const String&b){VersionParts x=parseVersion(a),y=parseVersion(b);if(!x.valid||!y.valid)return 0;if(x.major!=y.major)return x.major>y.major?1:-1;if(x.minor!=y.minor)return x.minor>y.minor?1:-1;if(x.patch!=y.patch)return x.patch>y.patch?1:-1;if(x.suffix==y.suffix)return 0;if(!x.suffix)return 1;if(!y.suffix)return -1;return x.suffix>y.suffix?1:-1;}
static bool verifySignature(const String&payload,const String&sig64){uint8_t sig[96];size_t sigLen=0;if(mbedtls_base64_decode(sig,sizeof(sig),&sigLen,(const unsigned char*)sig64.c_str(),sig64.length())!=0||!sigLen)return false;uint8_t digest[32];if(mbedtls_sha256((const unsigned char*)payload.c_str(),payload.length(),digest,0)!=0)return false;mbedtls_pk_context pk;mbedtls_pk_init(&pk);int rc=mbedtls_pk_parse_public_key(&pk,(const unsigned char*)OTA_PUBLIC_KEY,sizeof(OTA_PUBLIC_KEY));if(rc==0)rc=mbedtls_pk_verify(&pk,MBEDTLS_MD_SHA256,digest,sizeof(digest),sig,sigLen);mbedtls_pk_free(&pk);return rc==0;}
static bool parsePayload(const String&payload,RemoteStatus&out){bool gv=false,gb=false,gs=false,gc=false,gu=false;int start=0;while(start<(int)payload.length()){int nl=payload.indexOf('\n',start);if(nl<0)nl=payload.length();String line=payload.substring(start,nl);start=nl+1;if(!line.length())continue;int eq=line.indexOf('=');if(eq<=0)return false;String k=line.substring(0,eq),v=line.substring(eq+1);if(k=="version"&&!gv){out.availableVersion=v;gv=true;}else if(k=="bytes"&&!gb){if(!v.length())return false;for(size_t i=0;i<v.length();i++)if(v[i]<'0'||v[i]>'9')return false;out.bytes=(size_t)v.toInt();gb=true;}else if(k=="sha256"&&!gs){out.sha256=v;out.sha256.toLowerCase();gs=true;}else if(k=="commit"&&!gc){out.commit=v;out.commit.toLowerCase();gc=true;}else if(k=="url"&&!gu){out.url=v;gu=true;}else return false;}if(!gv||!gb||!gs||!gc||!gu)return false;if(!parseVersion(out.availableVersion).valid||out.bytes==0||out.bytes>=OTA_SLOT_BYTES||!allHex(out.sha256,64)||!allHex(out.commit,40))return false;String expected=String(OTA_RELEASE_PREFIX)+out.availableVersion+"/and_"+out.availableVersion+".bin";return out.url==expected;}
static String statusJson(const char*current){JsonDocument d;d["checked"]=last.checked;d["ok"]=last.ok;d["signatureValid"]=last.signatureValid;d["currentVersion"]=current;d["updateAvailable"]=last.updateAvailable;d["autoInstall"]=false;d["downloadEnabled"]=false;d["manifestUrl"]=OTA_MANIFEST_URL;d["otaSlotBytes"]=OTA_SLOT_BYTES;d["httpStatus"]=last.httpStatus;d["message"]=last.message;if(last.availableVersion.length())d["availableVersion"]=last.availableVersion;if(last.bytes)d["bytes"]=(uint32_t)last.bytes;if(last.sha256.length())d["sha256"]=last.sha256;if(last.commit.length())d["commit"]=last.commit;if(last.url.length())d["url"]=last.url;String j;serializeJson(d,j);return j;}
String remoteUpdateStatusJson(const char*current){return statusJson(current);}
String remoteUpdateCheckJson(const char*current){last=RemoteStatus();last.checked=true;if(WiFi.status()!=WL_CONNECTED){last.message="Wi-Fi is not connected";return statusJson(current);}WiFiClientSecure client;client.setInsecure();HTTPClient http;http.setConnectTimeout(6000);http.setTimeout(8000);if(!http.begin(client,OTA_MANIFEST_URL)){last.message="Could not open the remote manifest URL";return statusJson(current);}last.httpStatus=http.GET();if(last.httpStatus!=HTTP_CODE_OK){last.message=String("Manifest request failed (HTTP ")+String(last.httpStatus)+")";http.end();return statusJson(current);}String body=http.getString();http.end();if(body.length()==0||body.length()>4096){last.message="Remote manifest size is invalid";return statusJson(current);}JsonDocument d;if(deserializeJson(d,body)||!d.is<JsonObject>()||(d["schema"]|0)!=1){last.message="Remote manifest format is invalid";return statusJson(current);}String payload=d["payload"]|String(""),sig=d["signature"]|String("");if(!payload.length()||!sig.length()){last.message="Remote manifest is missing its signed payload";return statusJson(current);}last.signatureValid=verifySignature(payload,sig);if(!last.signatureValid){last.message="Remote manifest signature is invalid";return statusJson(current);}if(!parsePayload(payload,last)){last.message="Signed manifest payload is invalid";return statusJson(current);}int cmp=compareVersion(last.availableVersion,String(current));last.ok=true;last.updateAvailable=cmp>0;if(cmp>0)last.message=String("Verified update available: ")+last.availableVersion+" (download/install disabled in this transitional release)";else if(cmp==0)last.message=String("Signed manifest verified. Anderson Home ")+current+" is current.";else last.message=String("Signed manifest verified but advertises older firmware ")+last.availableVersion+"; downgrade is blocked.";return statusJson(current);}
