#include "WiFi.h"
#include <cstring>
WiFiClass WiFi;
void WiFiClass::ensureInit(){if(initialized_)return;esp_netif_init();esp_err_t e=esp_event_loop_create_default();(void)e;staNetif_=esp_netif_create_default_wifi_sta();apNetif_=esp_netif_create_default_wifi_ap();wifi_init_config_t cfg=WIFI_INIT_CONFIG_DEFAULT();if(esp_wifi_init(&cfg)!=ESP_OK)return;mutex_=xSemaphoreCreateMutex();esp_event_handler_register(WIFI_EVENT,ESP_EVENT_ANY_ID,&WiFiClass::eventThunk,this);esp_event_handler_register(IP_EVENT,ESP_EVENT_ANY_ID,&WiFiClass::eventThunk,this);initialized_=true;}
void WiFiClass::eventThunk(void* a,esp_event_base_t b,int32_t id,void* d){static_cast<WiFiClass*>(a)->handleEvent(b,id,d);}
void WiFiClass::handleEvent(esp_event_base_t base,int32_t id,void* data){arduino_event_info_t info{};if(base==WIFI_EVENT&&id==WIFI_EVENT_STA_DISCONNECTED){gotIp_=false;staIp_=0;auto* ev=(wifi_event_sta_disconnected_t*)data;if(ev)info.wifi_sta_disconnected.reason=ev->reason;if(callback_)callback_(ARDUINO_EVENT_WIFI_STA_DISCONNECTED,info);}else if(base==IP_EVENT&&id==IP_EVENT_STA_GOT_IP){auto* ev=(ip_event_got_ip_t*)data;gotIp_=true;staIp_=ev?ev->ip_info.ip.addr:0;if(callback_)callback_(ARDUINO_EVENT_WIFI_STA_GOT_IP,info);}else if(base==IP_EVENT&&id==IP_EVENT_STA_LOST_IP){gotIp_=false;staIp_=0;if(callback_)callback_(ARDUINO_EVENT_WIFI_STA_LOST_IP,info);}else if(base==WIFI_EVENT&&id==WIFI_EVENT_SCAN_DONE){uint16_t n=0;esp_wifi_scan_get_ap_num(&n);std::vector<wifi_ap_record_t> rec(n);if(n)esp_wifi_scan_get_ap_records(&n,rec.data());if(mutex_)xSemaphoreTake(mutex_,portMAX_DELAY);scans_.clear();for(uint16_t i=0;i<n;i++){ScanItem x;x.ssid=(const char*)rec[i].ssid;x.rssi=rec[i].rssi;scans_.push_back(x);}scanRunning_=false;if(mutex_)xSemaphoreGive(mutex_);}}
bool WiFiClass::mode(wifi_mode_compat_t m){ensureInit();wifi_mode_t mode=WIFI_MODE_NULL;if(m==WIFI_STA)mode=WIFI_MODE_STA;else if(m==WIFI_AP)mode=WIFI_MODE_AP;else if(m==WIFI_AP_STA)mode=WIFI_MODE_APSTA;if(esp_wifi_set_mode(mode)!=ESP_OK)return false;if(!started_&&mode!=WIFI_MODE_NULL){esp_err_t e=esp_wifi_start();if(e!=ESP_OK&&e!=ESP_ERR_INVALID_STATE)return false;started_=true;}return true;}
void WiFiClass::setSleep(bool sleep){ensureInit();esp_wifi_set_ps(sleep?WIFI_PS_MIN_MODEM:WIFI_PS_NONE);}
void WiFiClass::begin(const char* ssid,const char* pass){ensureInit();mode(WIFI_STA);wifi_config_t c{};strncpy((char*)c.sta.ssid,ssid?ssid:"",sizeof(c.sta.ssid)-1);strncpy((char*)c.sta.password,pass?pass:"",sizeof(c.sta.password)-1);c.sta.threshold.authmode=WIFI_AUTH_OPEN;c.sta.pmf_cfg.capable=true;c.sta.pmf_cfg.required=false;esp_wifi_set_config(WIFI_IF_STA,&c);esp_wifi_connect();}
bool WiFiClass::reconnect(){ensureInit();return esp_wifi_connect()==ESP_OK;}
bool WiFiClass::softAP(const char* ssid,const char* pass){ensureInit();wifi_mode_t cur=WIFI_MODE_NULL;esp_wifi_get_mode(&cur);mode(cur==WIFI_MODE_STA||cur==WIFI_MODE_APSTA?WIFI_AP_STA:WIFI_AP);wifi_config_t c{};strncpy((char*)c.ap.ssid,ssid?ssid:"",sizeof(c.ap.ssid)-1);c.ap.ssid_len=strlen((char*)c.ap.ssid);strncpy((char*)c.ap.password,pass?pass:"",sizeof(c.ap.password)-1);c.ap.max_connection=4;c.ap.channel=1;c.ap.authmode=(pass&&strlen(pass)>=8)?WIFI_AUTH_WPA2_PSK:WIFI_AUTH_OPEN;return esp_wifi_set_config(WIFI_IF_AP,&c)==ESP_OK;}
IPAddress WiFiClass::softAPIP()const{esp_netif_ip_info_t i{};if(apNetif_)esp_netif_get_ip_info(apNetif_,&i);return IPAddress(i.ip.addr);}
String WiFiClass::SSID()const{wifi_ap_record_t r{};if(gotIp_&&esp_wifi_sta_get_ap_info(&r)==ESP_OK)return String((const char*)r.ssid);wifi_config_t c{};if(esp_wifi_get_config(WIFI_IF_STA,&c)==ESP_OK)return String((const char*)c.sta.ssid);return String();}
int32_t WiFiClass::RSSI()const{wifi_ap_record_t r{};return gotIp_&&esp_wifi_sta_get_ap_info(&r)==ESP_OK?r.rssi:0;}
String WiFiClass::SSID(int i)const{if(mutex_)xSemaphoreTake(mutex_,portMAX_DELAY);String s=(i>=0&&i<(int)scans_.size())?scans_[i].ssid:String();if(mutex_)xSemaphoreGive(mutex_);return s;}
int32_t WiFiClass::RSSI(int i)const{if(mutex_)xSemaphoreTake(mutex_,portMAX_DELAY);int32_t r=(i>=0&&i<(int)scans_.size())?scans_[i].rssi:0;if(mutex_)xSemaphoreGive(mutex_);return r;}
int WiFiClass::scanNetworks(bool async,bool showHidden,bool passive,uint32_t maxMs){ensureInit();wifi_scan_config_t c{};c.show_hidden=showHidden;c.scan_type=passive?WIFI_SCAN_TYPE_PASSIVE:WIFI_SCAN_TYPE_ACTIVE;c.scan_time.active.min=30;c.scan_time.active.max=maxMs;c.scan_time.passive=maxMs;scanRunning_=true;esp_err_t e=esp_wifi_scan_start(&c,!async);if(e!=ESP_OK){scanRunning_=false;return WIFI_SCAN_FAILED;}if(async)return WIFI_SCAN_RUNNING;while(scanRunning_)vTaskDelay(pdMS_TO_TICKS(10));return scanComplete();}
int WiFiClass::scanComplete()const{if(scanRunning_)return WIFI_SCAN_RUNNING;if(mutex_)xSemaphoreTake(mutex_,portMAX_DELAY);int n=(int)scans_.size();if(mutex_)xSemaphoreGive(mutex_);return n;}
void WiFiClass::scanDelete(){if(mutex_)xSemaphoreTake(mutex_,portMAX_DELAY);scans_.clear();scanRunning_=false;if(mutex_)xSemaphoreGive(mutex_);}
