plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jasonhome.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.jasonhome.app'
        minSdk 26
        targetSdk 35
        versionCode 63
        versionName '5.0.3'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
