from pathlib import Path
import re

# Version metadata
Path('FIRMWARE_VERSION.txt').write_text('3.1.0\n')
readme=Path('README.md').read_text()
readme=re.sub(r'(Current firmware[^\n]*?v)3\.0\.29',r'\g<1>3.1.0',readme,count=1,flags=re.I)
readme=readme.replace('anderson-v3.0.29','anderson-v3.1.0')
Path('README.md').write_text(readme)

Path('firmware/RELEASE_NOTES_v3.1.0.md').write_text('''# Anderson Home v3.1.0\n\n- Removes unsupported Gradient from the firmware and UI; legacy Gradient/Fade/Rainbow names map safely to Breath.\n- Adds Original Colors (v3.0.28) / Modern Colors (v3.0.29) A/B event-color themes with persistent selection and generation-aware manual color overrides.\n- Redesigns interactive color controls as square, dimensional Anderson blue-glass tiles.\n- Keeps Schedule 1 and Schedule 2 controls under Settings > Schedules while removing their duplicate controls from the Schedules page.\n- Removes Enable All and Clear Month and the unused bulk-event API.\n- Makes supported calendar rules recur year-to-year and extends table-driven observances through the scheduler look-ahead range.\n- Fixes holiday lead/trail windows with civil-date arithmetic across DST boundaries.\n- Fixes the live Favorite Colors API to return all 16 locked master colors.\n- Rejects over-capacity custom shows/schedules instead of silently deleting the oldest entry and adds checked linked-delete recovery.\n- Adds checked/staged settings and event-override persistence, dirty-field protection, stale-search suppression, server-side event search, Wi-Fi reset persistence, safe text rendering, PIN/session bookkeeping fixes, and verified firmware-return reporting.\n- Removes obsolete Gradient/bulk-control/polling code and other superseded paths.\n- Adds permanent successful-build cleanup that retains the two newest Anderson object/PlatformIO cache generations and removes older matching GitHub Actions caches.\n- Preserves the 210-event Modern color assignments, all 16 master colors, Favorites persistence, Jason/Shirley profiles, two-controller BLE, Schedule 2 dawn/30% behavior, partitions, and saved-data compatibility.\n- OTA is intentionally not advanced.\n''')

# Permanent cache cleanup script
cache=Path('.github/scripts/anderson-cache-cleanup.sh')
cache.write_text('''#!/usr/bin/env bash\nset -euo pipefail\n: "${GH_TOKEN:?GH_TOKEN is required}"\nrepo="${GITHUB_REPOSITORY:?GITHUB_REPOSITORY is required}"\ntmp="$(mktemp)"\ntrap 'rm -f "$tmp"' EXIT\ngh cache list --repo "$repo" --limit 100 --json id,key,createdAt,lastAccessedAt > "$tmp"\npython3 - "$tmp" <<'PY' | while read -r cache_id; do\nimport json,sys\nrows=json.load(open(sys.argv[1],encoding='utf-8'))\nprefixes=('Linux-anderson-objects-v1-','Linux-pio-v1-')\nfor prefix in prefixes:\n    group=[r for r in rows if str(r.get('key','')).startswith(prefix)]\n    group.sort(key=lambda r:(r.get('lastAccessedAt') or '',r.get('createdAt') or ''),reverse=True)\n    for row in group[2:]: print(row['id'])\nPY\n  [ -z "$cache_id" ] || gh cache delete "$cache_id" --repo "$repo" || true\ndone\n''')

# Standard build workflow gets post-success cache housekeeping.
w=Path('.github/workflows/compile-anderson-home-multi.yml'); text=w.read_text()
needle='''      - name: Retain current build plus one backup\n        if: success()\n        env:\n          GH_TOKEN: ${{ github.token }}\n          CLEAN_RELEASES: '0'\n        run: bash .github/scripts/anderson-retention.sh\n'''
insert=needle+'''      - name: Clean stale Anderson build caches\n        if: success()\n        env:\n          GH_TOKEN: ${{ github.token }}\n        run: bash .github/scripts/anderson-cache-cleanup.sh\n'''
if needle not in text: raise AssertionError('retention step not found')
text=text.replace(needle,insert,1)
w.write_text(text)

# Permanent source regression checks for this major revision.
Path('tools/test_v310_regressions.py').write_text(r'''from pathlib import Path\nimport re\n\ndef t(p): return Path(p).read_text()\nmain=t('firmware/src/main.cpp'); web=t('firmware/web/index.html'); mock=t('firmware/web/v3_mockup.js'); ev=t('firmware/src/EventCatalog.cpp'); sched=t('firmware/src/Scheduler.cpp'); types=t('firmware/include/Types.h'); ble=t('firmware/src/BleController.cpp'); workflow=t('.github/workflows/compile-anderson-home-multi.yml')\nassert 'Effect::Gradient' not in ev+ble+sched+types\nassert 'Gradient</option>' not in web and "effect:'Gradient'" not in web\nassert 'v3FxGradient' not in mock and 'data-effect="Gradient"' not in mock\nassert 'ANDERSON_COLOR_PALETTE_COUNT' in main and 'server.on("/api/colors"' in main\nassert '/api/events/bulk' not in main+web and 'enableMonth' not in web and 'clearMonth' not in web\nassert 'eventsSchedule1Toggle' not in web and 'eventsSchedule2Toggle' not in web\nassert 'eventWindowActiveOn(i,l,cfg->leadDays,cfg->trailDays)' in sched\nassert 't.effect=Effect::Breath' in sched\nassert 'Custom-light capacity reached (12)' in main and 'Schedule capacity reached (32)' in main\nassert 'server.on("/api/events/search"' in main and 'eventRequestGeneration' in web\nassert 'server.on("/api/event-color-theme"' in main and 'eventColorsOriginal' in web and 'eventColorsModern' in web\nassert 'eventColorThemeGeneration' in main and 'colorGeneration' in main\nassert 'saveSettings(next)' in main and 'Event override write failed' in main\nassert 'if(tries>=8)' not in web and 'otaExpectedPartition' in web\nassert 'PinAttemptState pinAttempts[6]' in main\nassert 'store.clearWiFi()' in main and 'saveWiFi("","")' in t('firmware/src/SettingsStore.cpp')\nfor row in ['{"evt028",2037,2,15}','{"evt030",2037,10,11}','{"evt047",2037,11,9}','{"evt096",2037,1,27}','{"evt177",2037,10,18}','{"evt192",2037,11,7}']: assert row in ev,row\nassert 'anderson-cache-cleanup.sh' in workflow\nassert 'setInterval(()=>qa(\'select[data-v3-effect-preview="1"]\')' not in mock\nassert t('FIRMWARE_VERSION.txt').strip()=='3.1.0'\nprint('v3.1.0 regression source checks passed')\n'''.replace('\\n','\n'))
print('v3.1.0 CI/metadata patch applied')
