plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jlc3718.silveradostreambrowser'
    compileSdk 35

    defaultConfig {
        applicationId 'com.jlc3718.silveradostreambrowser'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '1.0.3'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError true
        checkReleaseBuilds true
    }
}
